# Generated by Django 3.2.25 on 2024-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casnet', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.BinaryField(),
        ),
    ]
